### ISSUE TITLE
Plugin not showing up in Cura 5.4 MacOS

### ISSUE THREAD

**Issue by heathentrucker** [Molodos/ElegooNeptuneThumbnails#18]
I went into the marketplace and reenabled the plugin in there which I had disabled before installing from GitHub as part of the troubleshooting process and when I quit Cura again and opened it back up the plugin showed up. Not sure if it was a combination of the marketplace plugin and the GitHub version being installed. I have attached the logs as you requested. 
[cura.log](https://github.com/Molodos/ElegooNeptuneThumbnails/files/12602371/cura.log)

**General information (please complete the following information):**
 - Printer: [e.g. ELEGOO Neptune 3 Pro]
 - Printer Firmeware Version: [found in printer menu]
 - Cura Version: [e.g. 5.4.0]
 - Plugin Version: [e.g. 2.2.0]
 - Operating System: [e.g. Windows 11]

**Describe the bug:**
A clear and concise description of what the bug is

**Steps to reproduce:**
1. Load '...'
2. Slice '...'
3. Save '...'
4. Error

**Additional information:**
Add additional information (optional)

**Comment by Molodos** [comment]
Thanks for the details, now I know exactly what happened, Here a quick description so you also know:
First you installed the outdated version from marketplace, which doesn't have the GUI yet, so it seemed to not show up but it was probably correctly installed. Then you disabled it and after the GitHub installation the disabled plugin was updated (because GitHub has a newer version) but stayed disabled. Therefore everything was installed correctly but unfortunately disabled and therefore the GUI wouldn't show up.
So it looks like everything worked as it should have worked out, but I will keep this issue, so others can find it if they stumble over similar problems.
